# Generated by Django 4.0.3 on 2022-03-21 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_professional_module', models.CharField(blank=True, db_column='Индекс_ПМ', max_length=60, null=True)),
                ('name_professional_module', models.CharField(blank=True, db_column='Название_ПМ', max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_theme', models.CharField(blank=True, db_column='Название_Темы', max_length=45, null=True)),
                ('id_professional_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ID_ПМ', to='GEK_API.professionalmodule')),
            ],
        ),
    ]
