# Generated by Django 4.0.3 on 2022-03-21 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GEK_API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(blank=True, db_column='Name_Group', max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_speciality', models.CharField(blank=True, db_column='Name_Speciality', max_length=60, null=True)),
                ('code_speciality', models.CharField(blank=True, db_column='Code_Speciality', max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, db_column='Surname', max_length=60, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=60, null=True)),
                ('patronymic', models.CharField(blank=True, db_column='Patronymic', max_length=60, null=True)),
                ('average_grade', models.FloatField(blank=True, db_column='Average_grade', null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, db_column='Date_Of_Birth', null=True)),
                ('id_group', models.ForeignKey(db_column='ID_Group', on_delete=django.db.models.deletion.CASCADE, to='GEK_API.group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='id_speciality',
            field=models.ForeignKey(db_column='ID_Speciality', on_delete=django.db.models.deletion.CASCADE, to='GEK_API.speciality'),
        ),
    ]
