# Generated by Django 4.0.3 on 2022-03-21 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GEK_API', '0002_group_speciality_student_group_id_speciality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, db_column='Surname', max_length=45, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=45, null=True)),
                ('patronymic', models.CharField(blank=True, db_column='Patronymic', max_length=45, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, db_column='Date_Of_Birth', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiplomaWork',
            fields=[
                ('id_diploma_work', models.AutoField(db_column='ID_Diploma_Work', primary_key=True, serialize=False)),
                ('id_student', models.ForeignKey(db_column='ID_Student', on_delete=django.db.models.deletion.CASCADE, to='GEK_API.student')),
                ('id_teacher', models.ForeignKey(db_column='ID_Teacher', on_delete=django.db.models.deletion.CASCADE, to='GEK_API.teacher')),
                ('id_themes', models.ForeignKey(db_column='ID_Themes', on_delete=django.db.models.deletion.CASCADE, to='GEK_API.theme')),
            ],
        ),
    ]
