# Generated by Django 4.0.3 on 2022-03-21 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GEK_API', '0005_themesofprorotocol'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingGek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_meetings_gek', models.DateTimeField(blank=True, db_column='Date_Meetings_GEK', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantList',
            fields=[
                ('id_participants_list', models.AutoField(db_column='ID_participant_list', primary_key=True, serialize=False)),
                ('id_meeting_gek', models.ForeignKey(blank=True, db_column='ID_Meeting_GEK', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GEK_API.meetinggek')),
                ('id_member_gek', models.ForeignKey(blank=True, db_column='ID_Member_GEK', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='GEK_API.membergek')),
            ],
        ),
    ]
