# Generated by Django 4.0.3 on 2022-03-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GEK_API', '0007_generalprotocol_protocol_generalvaluationoftheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, db_column='Surname', max_length=60, null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=60, null=True)),
                ('patronymic', models.CharField(blank=True, db_column='Patronymic', max_length=60, null=True)),
                ('password', models.FloatField(blank=True, db_column='Password', null=True)),
            ],
        ),
    ]
